"""
The rendering package: a typed, backend-agnostic scene model between
solvers and renderers. Solvers declare WHAT to show (scene elements at
abstract grid locations, semantic colors); grids supply geometry;
renderers (ASCII, SVG, sheet/TSV) paint. This module re-exports the
solver-facing vocabulary.
"""

from aspuzzle.rendering.backend import (
    ALL_BACKENDS,
    ASCII_ONLY,
    CHARACTER_BACKENDS,
    SHEET_ONLY,
    SVG_ONLY,
    Backend,
    BackendSet,
)
from aspuzzle.rendering.color import ColorSpec, PaletteColor, Rgb
from aspuzzle.rendering.glyph import Glyph, glyph_for_value
from aspuzzle.rendering.scene import (
    CellFill,
    CellGlyph,
    CellLink,
    CellMark,
    CellPath,
    CellStyle,
    Edge,
    EdgeMark,
    EdgeSegment,
    EdgeWeight,
    Lattice,
    Layer,
    LayoutNeeds,
    OutsideLabel,
    Provenance,
    Scene,
    SceneElement,
    SceneStyle,
    Vertex,
    VertexMark,
)
from aspuzzle.rendering.spec import (
    AtomRule,
    Colorer,
    ColorLike,
    CustomRule,
    EdgeRule,
    FillRule,
    FromClues,
    FromPredicate,
    GlyphRule,
    LineLabels,
    LinkRule,
    PathRule,
    PredicateRef,
    RegionBorderRule,
    RegionBoundaryRule,
    RegionFillRule,
    RenderContext,
    RenderSpec,
    build_scene,
    digit_clues,
    filled_clue,
    overflow_clues,
    symbol_clues,
    symbol_colorer,
)

__all__ = [
    "ALL_BACKENDS",
    "ASCII_ONLY",
    "CHARACTER_BACKENDS",
    "SHEET_ONLY",
    "SVG_ONLY",
    "AtomRule",
    "Backend",
    "BackendSet",
    "CellFill",
    "CellGlyph",
    "CellLink",
    "CellMark",
    "CellPath",
    "CellStyle",
    "ColorLike",
    "ColorSpec",
    "Colorer",
    "CustomRule",
    "Edge",
    "EdgeMark",
    "EdgeRule",
    "EdgeSegment",
    "EdgeWeight",
    "FillRule",
    "FromClues",
    "FromPredicate",
    "Glyph",
    "GlyphRule",
    "Lattice",
    "Layer",
    "LayoutNeeds",
    "LineLabels",
    "LinkRule",
    "OutsideLabel",
    "PaletteColor",
    "PathRule",
    "PredicateRef",
    "Provenance",
    "RegionBorderRule",
    "RegionBoundaryRule",
    "RegionFillRule",
    "RenderContext",
    "RenderSpec",
    "Rgb",
    "Scene",
    "SceneElement",
    "SceneStyle",
    "Vertex",
    "VertexMark",
    "build_scene",
    "digit_clues",
    "filled_clue",
    "glyph_for_value",
    "overflow_clues",
    "symbol_clues",
    "symbol_colorer",
]
