"""
The grid-agnostic SVG renderer: the second consumer of the Scene, mapping
elements mechanically onto SVG markup through whatever SvgGeometry the
scene's grid supplies. Geometries speak unit-cell coordinates; the
renderer scales by cell_size and folds the viewBox from every point it
draws plus a quarter-cell margin. Paint-or-skip arbitration comes from
the shared ScenePainter core: cell content filters on cell membership,
edges and vertices through the geometry's lattice predicates.
"""

import math
from itertools import groupby
from typing import TYPE_CHECKING, Final, assert_never

from aspuzzle.rendering.backend import Backend
from aspuzzle.rendering.color import ColorSpec
from aspuzzle.rendering.glyph import Glyph
from aspuzzle.rendering.painter import ScenePainter
from aspuzzle.rendering.scene import (
    CellFill,
    CellGlyph,
    CellLink,
    CellMark,
    CellPath,
    Edge,
    EdgeMark,
    EdgeSegment,
    EdgeWeight,
    Layer,
    MarkElement,
    OutsideLabel,
    Provenance,
    Scene,
    SceneStyle,
    VertexMark,
)
from aspuzzle.rendering.svg.geometry import Point, SvgGeometry, TextAnchor
from aspuzzle.rendering.svg.markup import escape
from aspuzzle.rendering.svg.theme import DEFAULT_SVG_THEME, SvgTheme

if TYPE_CHECKING:
    from aspuzzle.grids.base import GridCell
    from aspuzzle.rendering.gridview import RenderGrid

GENERATOR_COMMENT: Final = "<!-- Generated by ASPuzzle https://github.com/jolyonb/aspuzzle -->"

# Bounds-folding heuristic: text extends ~0.6 em per character from its
# anchor, so outside labels never clip the viewBox whatever anchoring
# their geometry chose
_GLYPH_WIDTH_EM: Final = 0.6

# First code point of the emoji-leaning symbol blocks (Miscellaneous
# Symbols onward). Text containing any such character renders in the
# emoji class — smaller and unhaloed (Firefox drops color-emoji glyphs
# entirely from stroked SVG text, and emoji carry their own solid
# silhouette). The floor also catches text symbols like ★ or ✓; refine
# to explicit emoji ranges if a glyph above it ever wants the halo.
_EMOJI_BLOCK_START: Final = 0x2600


def _fmt(value: float) -> str:
    """Compact deterministic coordinate formatting: fixed-point, trailing
    zeros trimmed, negative zero normalized."""
    text = f"{value:.4f}".rstrip("0").rstrip(".")
    return "0" if text in ("-0", "") else text


# A drawn edge segment: two endpoints in final formatted coordinates,
# exact-match keys for chaining
type _Segment = tuple[tuple[str, str], tuple[str, str]]


def _chain_segments(segments: list[_Segment]) -> str:
    """One path `d` covering the segments, chained into subpaths by
    walking shared endpoints: open runs start at odd-degree endpoints and
    end butt-flush; fully-circled boundaries come out as closed subpaths
    (Z), so corners are stroke joins, never caps."""
    adjacency: dict[tuple[str, str], list[tuple[int, tuple[str, str]]]] = {}
    for index, (a, b) in enumerate(segments):
        adjacency.setdefault(a, []).append((index, b))
        adjacency.setdefault(b, []).append((index, a))
    for neighbors in adjacency.values():
        neighbors.sort(key=lambda entry: (entry[1], entry[0]))
    used = [False] * len(segments)

    def walk(start: tuple[str, str]) -> list[tuple[str, str]] | None:
        points = [start]
        current = start
        while True:
            for index, other in adjacency[current]:
                if not used[index]:
                    used[index] = True
                    points.append(other)
                    current = other
                    break
            else:
                return points if len(points) > 1 else None

    subpaths: list[str] = []
    odd_degree = sorted(point for point, neighbors in adjacency.items() if len(neighbors) % 2 == 1)
    for start in odd_degree + sorted(adjacency):
        while (points := walk(start)) is not None:
            closed = points[0] == points[-1]
            if closed:
                points = points[:-1]
            coords = " L ".join(f"{x} {y}" for x, y in points)
            subpaths.append(f"M {coords} Z" if closed else f"M {coords}")
    return " ".join(subpaths)


def _layer_name(layer: int) -> str:
    """data-layer value: the Layer name for named layers, the int for
    fine-grained tweaks between them."""
    try:
        return Layer(layer).name.lower().replace("_", "-")
    except ValueError:
        return str(layer)


class _Bounds:
    """Running min/max over drawn coordinates."""

    def __init__(self) -> None:
        self.min_x = math.inf
        self.min_y = math.inf
        self.max_x = -math.inf
        self.max_y = -math.inf

    def add(self, x: float, y: float) -> None:
        self.min_x = min(self.min_x, x)
        self.min_y = min(self.min_y, y)
        self.max_x = max(self.max_x, x)
        self.max_y = max(self.max_y, y)

    @property
    def empty(self) -> bool:
        return self.min_x > self.max_x


class SvgRenderer:
    """
    The grid-agnostic SVG painter: asks the scene's grid for its geometry,
    paints the substrate (hairline lattice / heavy frame / vertex dots per
    the SVG-effective SceneStyle), then every SVG-visible element in
    painter's order as <g data-layer=...> groups with data-provenance on
    each element, and sizes the viewBox from the points it drew. Contains
    zero grid-specific knowledge.
    """

    backend: Final = Backend.SVG

    def __init__(self, theme: SvgTheme = DEFAULT_SVG_THEME, cell_size: float = 64) -> None:
        self.theme = theme
        self.cell_size = cell_size

    def render(self, scene: Scene) -> str:
        painter = SvgPainter(scene.grid, scene.grid.svg_geometry(), self.theme, self.cell_size)
        style = scene.style_for(Backend.SVG)
        groups: list[tuple[str, list[str]]] = []
        substrate = painter.paint_substrate(style)
        if substrate:
            groups.append(("base", substrate))

        # The frame paints at Layer.FRAME rather than with the rest of the
        # substrate: a region border running out to the edge of the board ends
        # flush against the frame line, and painting it after the frame leaves
        # the border's stroke sitting on top of the black rule. Paths still go
        # over the frame — a loop is allowed to run along the boundary.
        frame = painter.paint_frame(style)

        def flush_frame() -> None:
            nonlocal frame
            if frame:
                groups.append(("frame", frame))
                frame = []

        for layer, elements in groupby(scene.sorted_elements(Backend.SVG), key=lambda element: element.layer):
            if layer > Layer.FRAME:
                flush_frame()
            for element in elements:
                painter.paint_element(element)
            markup = painter.take_group()
            if markup:
                groups.append((_layer_name(layer), markup))
        flush_frame()
        return painter.document(groups)


class SvgPainter(ScenePainter):
    """One render's worth of state: scaled-point emission with viewBox
    folding, and the paint operations turning elements into markup —
    scene walking and out-of-grid filtering come from ScenePainter."""

    geometry: SvgGeometry

    def __init__(self, grid: RenderGrid, geometry: SvgGeometry, theme: SvgTheme, cell_size: float) -> None:
        super().__init__(grid, geometry)
        self.theme = theme
        self.cell = cell_size
        self.bounds = _Bounds()
        self._group: list[str] = []  # the current layer group's markup
        # Edge segments accumulate here per layer group, keyed by
        # (stroke, width, provenance), and flush as chained <path>s: a
        # closed region boundary becomes a real closed loop (perfect
        # mitered corners), an open run ends butt-flush — nothing ever
        # pokes past the frame the way stroke caps would
        self._edge_runs: dict[tuple[str, float, str], list[_Segment]] = {}

    def take_group(self) -> list[str]:
        """The group's markup: elements in paint order, then the group's
        chained edge paths."""
        lines = self._group + self.flush_edges()
        self._group = []
        return lines

    # -- coordinate plumbing --

    def _xy(self, point: Point) -> tuple[float, float]:
        """Scale a unit-cell point to pixels, folding it into the bounds."""
        x, y = point.x * self.cell, point.y * self.cell
        self.bounds.add(x, y)
        return x, y

    def _provenance_color(self, provenance: Provenance) -> str:
        return self.theme.given_color if provenance is Provenance.GIVEN else self.theme.derived_color

    def _color(self, color: ColorSpec | None, provenance: Provenance) -> str:
        return self.theme.color(color) if color is not None else self._provenance_color(provenance)

    # -- substrate --

    def paint_frame(self, style: SceneStyle) -> list[str]:
        """The board's outside frame, painted at Layer.FRAME (see
        SvgRenderer.render) rather than with the rest of the substrate."""
        if style.heavy_frame and (edges := self.geometry.boundary_edges()):
            return [f'<path class="frame" d="{_chain_segments(self._edge_segments(edges))}"/>']
        return []

    def paint_substrate(self, style: SceneStyle) -> list[str]:
        lines: list[str] = []
        if style.hairline and (edges := self.geometry.all_edges()):
            lines.append(f'<path class="lattice" d="{_chain_segments(self._edge_segments(edges))}"/>')
        if style.vertex_dots:
            radius = _fmt(self.theme.dot_radius * self.cell)
            for vertex in self.geometry.all_vertices():
                x, y = self._xy(self.geometry.vertex_point(vertex))
                lines.append(f'<circle cx="{_fmt(x)}" cy="{_fmt(y)}" r="{radius}" fill="{self.theme.line_color}"/>')
        return lines

    def _edge_segments(self, edges: list[Edge]) -> list[_Segment]:
        segments: list[_Segment] = []
        for edge in edges:
            (x1, y1), (x2, y2) = (self._xy(p) for p in self.geometry.edge_endpoints(edge))
            segments.append(((_fmt(x1), _fmt(y1)), (_fmt(x2), _fmt(y2))))
        return segments

    # -- paint operations (dispatch and filtering live in ScenePainter) --

    def _prov(self, element: CellFill | CellGlyph | CellPath | CellLink | EdgeSegment) -> str:
        return f'data-provenance="{element.provenance.name.lower()}"'

    def paint_fill(self, element: CellFill) -> None:
        points = " ".join(f"{_fmt(x)},{_fmt(y)}" for x, y in map(self._xy, self.geometry.cell_polygon(element.cell)))
        fill = self.theme.color(element.color)
        resolved = _fmt(element.opacity if element.opacity is not None else self.theme.fill_opacity)
        self._group.append(
            f'<polygon points="{points}" fill="{fill}" fill-opacity="{resolved}" {self._prov(element)}/>'
        )

    def paint_glyph(self, element: CellGlyph) -> None:
        center = self.geometry.cell_center(element.cell)
        self._group.append(
            self._text(center, element.glyph.for_backend(Backend.SVG), element.color, element.provenance)
        )

    def paint_path(self, element: CellPath, directions: list[str]) -> None:
        cx, cy = self._xy(self.geometry.cell_center(element.cell))
        parts: list[str] = []
        for direction in directions:
            mx, my = self._xy(self._edge_midpoint(self.grid.edge(element.cell, direction)))
            parts.append(f"M {_fmt(cx)} {_fmt(cy)} L {_fmt(mx)} {_fmt(my)}")
        stroke = self._color(element.color, element.provenance)
        width = _fmt(self.theme.path_width * self.cell)
        self._group.append(
            f'<path class="path" d="{" ".join(parts)}" stroke="{stroke}" stroke-width="{width}" {self._prov(element)}/>'
        )

    def paint_link(self, element: CellLink, cells: list[GridCell]) -> None:
        if len(cells) == 2:
            (x1, y1), (x2, y2) = (self._xy(self.geometry.cell_center(cell)) for cell in cells)
            stroke = self._color(element.color, element.provenance)
            width = _fmt(self.theme.link_width * self.cell)
            self._group.append(
                f'<line class="path" x1="{_fmt(x1)}" y1="{_fmt(y1)}" x2="{_fmt(x2)}" y2="{_fmt(y2)}" '
                f'stroke="{stroke}" stroke-width="{width}" {self._prov(element)}/>'
            )
        if element.glyph is not None:
            text = element.glyph.for_backend(Backend.SVG)
            for cell in cells:
                self._group.append(self._text(self.geometry.cell_center(cell), text, element.color, element.provenance))

    def paint_edge(self, element: EdgeSegment) -> None:
        (x1, y1), (x2, y2) = (self._xy(p) for p in self.geometry.edge_endpoints(element.edge))
        stroke = self._color(element.color, element.provenance)
        fraction = self.theme.heavy_edge_width if element.weight is EdgeWeight.HEAVY else self.theme.edge_width
        key = (stroke, fraction * self.cell, element.provenance.name.lower())
        self._edge_runs.setdefault(key, []).append(((_fmt(x1), _fmt(y1)), (_fmt(x2), _fmt(y2))))

    def _mark_point(self, element: MarkElement) -> Point:
        """What anchors a mark, in unit-cell coordinates."""
        match element:
            case CellMark(cell=cell):
                return self.geometry.cell_center(cell)
            case EdgeMark(edge=edge):
                return self._edge_midpoint(edge)
            case VertexMark(vertex=vertex):
                return self.geometry.vertex_point(vertex)
            case _:
                assert_never(element)

    def paint_mark(self, element: MarkElement) -> None:
        point = self._mark_point(element)
        self._group.append(self._mark_markup(point, element.glyph, element.color, element.ring, element.provenance))

    def paint_label(self, element: OutsideLabel) -> None:
        anchored = self.geometry.outside_anchor(element.direction, element.index, element.offset)
        if anchored is None:
            return
        point, anchor = anchored
        self._group.append(
            self._text(point, element.glyph.for_backend(Backend.SVG), element.color, element.provenance, anchor)
        )

    def _edge_midpoint(self, edge: Edge) -> Point:
        p1, p2 = self.geometry.edge_endpoints(edge)
        return Point((p1.x + p2.x) / 2, (p1.y + p2.y) / 2)

    def flush_edges(self) -> list[str]:
        """The current layer group's edge segments, chained into paths."""
        lines = [
            f'<path class="edge" d="{_chain_segments(segments)}" stroke="{stroke}" '
            f'stroke-width="{_fmt(width)}" data-provenance="{prov}"/>'
            for (stroke, width, prov), segments in sorted(self._edge_runs.items())
        ]
        self._edge_runs.clear()
        return lines

    def _mark_markup(
        self,
        point: Point,
        glyph: Glyph | None,
        color: ColorSpec | None,
        ring: bool,
        provenance: Provenance,
    ) -> str:
        """One mark (CellMark/EdgeMark/VertexMark): its glyph as text, or
        the shape channel — a halo-filled open ring, or the default dot."""
        if glyph is not None:
            return self._text(point, glyph.for_backend(Backend.SVG), color, provenance)
        x, y = self._xy(point)
        paint = self._color(color, provenance)
        attrs = f'cx="{_fmt(x)}" cy="{_fmt(y)}" data-provenance="{provenance.name.lower()}"'
        if ring:
            radius = _fmt(self.theme.ring_radius * self.cell)
            width = _fmt(self.theme.ring_width * self.cell)
            return (
                f'<circle {attrs} r="{radius}" fill="{self.theme.halo_color}" stroke="{paint}" stroke-width="{width}"/>'
            )
        return f'<circle {attrs} r="{_fmt(self.theme.dot_radius * self.cell)}" fill="{paint}"/>'

    def _text(
        self,
        point: Point,
        text: str,
        color: ColorSpec | None,
        provenance: Provenance,
        anchor: TextAnchor = "middle",
    ) -> str:
        x, y = self._xy(point)
        if any(ord(character) >= _EMOJI_BLOCK_START for character in text):
            css_class = "emoji"
        else:
            css_class = ("bigtext", "medtext", "smalltext")[min(len(text), 3) - 1] + " halo"
        self._fold_text_extent(x, y, len(text), anchor)
        attrs = f'x="{_fmt(x)}" y="{_fmt(y)}" class="{css_class}" fill="{self._color(color, provenance)}"'
        if anchor != "middle":
            attrs += f' style="text-anchor:{anchor}"'
        return f'<text {attrs} data-provenance="{provenance.name.lower()}">{escape(text)}</text>'

    def _fold_text_extent(self, x: float, y: float, length: int, anchor: TextAnchor) -> None:
        font = self.theme.font_sizes[min(length, 3) - 1] * self.cell
        width = length * font * _GLYPH_WIDTH_EM
        left = width if anchor == "end" else width / 2 if anchor == "middle" else 0.0
        self.bounds.add(x - left, y - font / 2)
        self.bounds.add(x - left + width, y + font / 2)

    # -- document assembly --

    def document(self, groups: list[tuple[str, list[str]]]) -> str:
        if self.bounds.empty:
            # Nothing drawn (bare substrate off, empty scene): fall back to
            # the grid's own extent so the viewBox stays meaningful
            for cell in self.grid.all_cells():
                for point in self.geometry.cell_polygon(cell):
                    self._xy(point)
        pad = self.cell / 4
        min_x, min_y = self.bounds.min_x - pad, self.bounds.min_y - pad
        width = self.bounds.max_x - self.bounds.min_x + 2 * pad
        height = self.bounds.max_y - self.bounds.min_y + 2 * pad
        lines = [
            GENERATOR_COMMENT,
            f'<svg xmlns="http://www.w3.org/2000/svg" width="{_fmt(width)}" height="{_fmt(height)}" '
            f'viewBox="{_fmt(min_x)} {_fmt(min_y)} {_fmt(width)} {_fmt(height)}">',
            "<style>",
            self._stylesheet(),
            "</style>",
        ]
        if self.theme.background_color is not None:
            lines.append(
                f'<rect x="{_fmt(min_x)}" y="{_fmt(min_y)}" width="{_fmt(width)}" height="{_fmt(height)}" '
                f'fill="{self.theme.background_color}"/>'
            )
        for name, markup in groups:
            lines.append(f'<g data-layer="{name}">')
            lines.extend(markup)
            lines.append("</g>")
        lines.append("</svg>")
        return "\n".join(lines) + "\n"

    def _stylesheet(self) -> str:
        theme = self.theme
        sizes = [_fmt(fraction * self.cell) for fraction in theme.font_sizes]
        nudges = [_fmt(fraction * self.cell) for fraction in theme.text_nudges]
        halo = _fmt(theme.halo_width * self.cell)
        return "\n".join(
            [
                f"text {{ font-family: {theme.font_family}; text-anchor: middle; dominant-baseline: middle; }}",
                f".halo {{ paint-order: stroke fill; stroke: {theme.halo_color}; stroke-width: {halo}px;",
                "       stroke-linejoin: round; }",
                f".bigtext {{ font-size: {sizes[0]}px; transform: translate(0, {nudges[0]}px); }}",
                f".medtext {{ font-size: {sizes[1]}px; transform: translate(0, {nudges[1]}px); }}",
                f".smalltext {{ font-size: {sizes[2]}px; transform: translate(0, {nudges[2]}px); }}",
                f".emoji {{ font-size: {_fmt(theme.emoji_size * self.cell)}px; "
                f"transform: translate(0, {nudges[0]}px); }}",
                f".lattice {{ fill: none; stroke: {theme.line_color}; stroke-width: {_fmt(theme.hairline_width)};",
                "          stroke-linecap: butt; stroke-linejoin: bevel; vector-effect: non-scaling-stroke;",
                "          shape-rendering: geometricprecision; }",
                f".frame {{ fill: none; stroke: {theme.line_color}; stroke-width: {_fmt(theme.frame_width)};",
                "        stroke-linecap: butt; stroke-linejoin: miter; vector-effect: non-scaling-stroke;",
                "        shape-rendering: geometricprecision; }",
                ".edge { fill: none; stroke-linecap: butt; stroke-linejoin: miter;",
                "       shape-rendering: geometricprecision; }",
                ".path { fill: none; stroke-linecap: round; stroke-linejoin: round;",
                "       shape-rendering: geometricprecision; }",
            ]
        )
