"""
Fragment-level tests for the SVG renderer: markup safety, provenance
styling, viewBox folding, substrate flags, out-of-grid pre-filtering —
the behaviors the byte-level goldens can't explain when they change.
"""

import re

from aspuzzle.grids.base import Grid
from aspuzzle.rendering import (
    CellFill,
    CellGlyph,
    CellLink,
    CellMark,
    CellPath,
    Edge,
    EdgeMark,
    EdgeSegment,
    EdgeWeight,
    Glyph,
    OutsideLabel,
    PaletteColor,
    Provenance,
    Rgb,
    Scene,
    SceneStyle,
    Vertex,
    VertexMark,
)
from aspuzzle.rendering.svg import DEFAULT_SVG_PALETTE, SvgRenderer
from tests.rendering.test_grid_topology import rect_3x4


def make_scene(style: SceneStyle | None = None) -> tuple[Grid, Scene]:
    grid = rect_3x4()
    return grid, Scene(grid, style=style if style is not None else SceneStyle())


def view_box(svg: str) -> tuple[float, float, float, float]:
    match = re.search(r'viewBox="([^"]+)"', svg)
    assert match is not None
    a, b, c, d = (float(part) for part in match.group(1).split())
    return a, b, c, d


def test_document_shell() -> None:
    _grid, scene = make_scene()
    svg = SvgRenderer().render(scene)
    lines = svg.splitlines()
    assert lines[0] == "<!-- Generated by ASPuzzle https://github.com/jolyonb/aspuzzle -->"
    assert lines[1].startswith('<svg xmlns="http://www.w3.org/2000/svg"')
    assert svg.endswith("</svg>\n")
    # Default substrate: hairline lattice and heavy frame, no dots
    assert 'class="lattice"' in svg
    assert 'class="frame"' in svg
    assert "<circle" not in svg
    # 4 cols x 3 rows at 64px/cell plus a quarter-cell margin each side
    assert view_box(svg) == (-16.0, -16.0, 288.0, 224.0)
    # The theme's colors assume the background they declare: an explicit
    # viewBox-covering white rect, ahead of everything drawn
    assert '<rect x="-16" y="-16" width="288" height="224" fill="#ffffff"/>' in svg


def test_render_is_deterministic() -> None:
    def build() -> str:
        grid, scene = make_scene()
        cells = list(grid.all_cells())
        scene.add(CellFill(cells[5], PaletteColor.GREEN), CellGlyph(cells[0], Glyph("7")))
        return SvgRenderer().render(scene)

    assert build() == build()


def test_glyph_text_is_escaped() -> None:
    grid, scene = make_scene()
    scene.add(CellGlyph(next(grid.all_cells()), Glyph("<")))
    svg = SvgRenderer().render(scene)
    assert ">&lt;</text>" in svg


def test_emoji_class_skips_halo_and_shrinks() -> None:
    # Emoji get their own class: smaller (their ink fills the em square)
    # and unstroked — Firefox drops color-emoji glyphs from stroked text
    grid, scene = make_scene()
    cells = list(grid.all_cells())
    scene.add(CellGlyph(cells[0], Glyph("5")), CellGlyph(cells[1], Glyph("⛺")))
    svg = SvgRenderer().render(scene)
    assert re.search(r'<text [^>]*class="bigtext halo"[^>]*>5</text>', svg) is not None
    assert re.search(r'<text [^>]*class="emoji"[^>]*>⛺</text>', svg) is not None
    assert ".emoji { font-size: 40px;" in svg


def test_svg_glyph_variant_wins() -> None:
    grid, scene = make_scene()
    scene.add(CellGlyph(next(grid.all_cells()), Glyph("A", svg="⛺")))
    svg = SvgRenderer().render(scene)
    assert ">⛺</text>" in svg
    assert ">A</text>" not in svg


def test_provenance_styles_text() -> None:
    grid, scene = make_scene()
    cells = list(grid.all_cells())
    scene.add(
        CellGlyph(cells[0], Glyph("5"), provenance=Provenance.GIVEN),
        CellGlyph(cells[1], Glyph("6")),
    )
    svg = SvgRenderer().render(scene)
    given = re.search(r'<text [^>]*data-provenance="given"[^>]*>5</text>', svg)
    derived = re.search(r'<text [^>]*data-provenance="derived"[^>]*>6</text>', svg)
    assert given is not None and derived is not None
    assert 'fill="#000000"' in given.group(0)
    assert 'fill="#1d6ae5"' in derived.group(0)


def test_palette_and_rgb_colors() -> None:
    grid, scene = make_scene()
    cells = list(grid.all_cells())
    scene.add(CellFill(cells[0], PaletteColor.GREEN), CellFill(cells[1], Rgb(200, 100, 50)))
    svg = SvgRenderer().render(scene)
    assert f'fill="{DEFAULT_SVG_PALETTE[PaletteColor.GREEN]}"' in svg
    assert 'fill="#c86432"' in svg


def test_edge_weights_scale_stroke() -> None:
    grid, scene = make_scene()
    cells = list(grid.all_cells())
    scene.add(
        EdgeSegment(grid.edge(cells[0], "e")),
        EdgeSegment(grid.edge(cells[5], "s"), weight=EdgeWeight.HEAVY),
    )
    svg = SvgRenderer().render(scene)
    widths = [float(w) for w in re.findall(r'<path class="edge"[^>]*stroke-width="([^"]+)"', svg)]
    assert len(widths) == 2
    assert widths[1] == 2 * widths[0]


def test_edge_segments_chain_into_paths() -> None:
    grid, scene = make_scene()
    cell = grid.cell_at((2, 2))
    assert cell is not None
    corner_cell = grid.cell_at((1, 4))
    assert corner_cell is not None
    # A fully-circled cell and, in a different color, an L-corner
    scene.add(*(EdgeSegment(grid.edge(cell, direction)) for direction in "nesw"))
    scene.add(
        EdgeSegment(grid.edge(corner_cell, "s"), color=PaletteColor.RED),
        EdgeSegment(grid.edge(corner_cell, "w"), color=PaletteColor.RED),
    )
    svg = SvgRenderer().render(scene)
    paths = re.findall(r'<path class="edge" d="([^"]+)"', svg)
    assert len(paths) == 2  # one per style, not one per segment
    closed = [d for d in paths if d.endswith("Z")]
    open_runs = [d for d in paths if not d.endswith("Z")]
    assert len(closed) == 1 and closed[0].count("M") == 1  # the loop: one closed subpath
    assert len(open_runs) == 1 and open_runs[0].count("L") == 2  # the corner: one chained run


def test_cell_path_runs_center_to_edge_midpoints() -> None:
    grid, scene = make_scene()
    cell = grid.cell_at((2, 2))
    assert cell is not None
    scene.add(CellPath(cell, frozenset({"e", "s"}), color=PaletteColor.CYAN))
    svg = SvgRenderer().render(scene)
    match = re.search(r'<path class="path" d="([^"]+)"', svg)
    assert match is not None
    # Cell (2,2) at 64px/cell: center (96, 96), east midpoint (128, 96),
    # south midpoint (96, 128); one center-to-midpoint stroke per direction
    assert match.group(1) == "M 96 96 L 128 96 M 96 96 L 96 128"


def test_cell_link_draws_connector_and_glyphs() -> None:
    grid, scene = make_scene()
    cells = list(grid.all_cells())
    scene.add(CellLink(cells[0], cells[1], glyph=Glyph("x"), color=PaletteColor.MAGENTA))
    svg = SvgRenderer().render(scene)
    assert re.search(r'<line class="path"[^>]*stroke="#d23be7"', svg) is not None
    assert len(re.findall(r">x</text>", svg)) == 2


def test_ring_and_edge_marks() -> None:
    grid, scene = make_scene()
    cell = grid.cell_at((2, 2))
    assert cell is not None
    scene.add(CellMark(cell, ring=True), EdgeMark(grid.edge(cell, "e")))
    svg = SvgRenderer().render(scene)
    # Ring: halo-filled open circle at the cell center (96, 96)
    ring = re.search(r'<circle cx="96" cy="96" [^>]*/>', svg)
    assert ring is not None
    assert 'r="9"' in ring.group(0) and 'fill="#ffffff"' in ring.group(0) and 'stroke-width="3.5"' in ring.group(0)
    # Default dot at the east edge midpoint (128, 96)
    dot = re.search(r'<circle cx="128" cy="96" [^>]*/>', svg)
    assert dot is not None
    assert 'r="4"' in dot.group(0) and 'fill="#1d6ae5"' in dot.group(0)


def test_vertex_mark_default_dot() -> None:
    grid, scene = make_scene()
    cell = next(grid.all_cells())
    scene.add(VertexMark(grid.vertex(cell, "se"), color=PaletteColor.RED))
    svg = SvgRenderer().render(scene)
    assert re.search(r'<circle [^>]*data-provenance="derived" r="4" fill="#e6261f"/>', svg) is not None


def test_outside_label_anchor_and_bounds() -> None:
    _grid, bare_scene = make_scene()
    bare = view_box(SvgRenderer().render(bare_scene))

    _grid, scene = make_scene()
    scene.add(OutsideLabel("e", 2, Glyph("10")))
    svg = SvgRenderer().render(scene)
    label = re.search(r"<text [^>]*>10</text>", svg)
    assert label is not None
    # Centered in the virtual cell one step left of column 1
    assert 'x="-32" y="96"' in label.group(0)
    assert "text-anchor" not in label.group(0)
    # The left-ring label expands the viewBox leftward past the bare extent
    assert view_box(svg)[0] < bare[0]


def test_out_of_range_label_skipped() -> None:
    _grid, bare_scene = make_scene()
    bare = view_box(SvgRenderer().render(bare_scene))
    _grid, scene = make_scene()
    scene.add(OutsideLabel("e", 9, Glyph("7")))
    svg = SvgRenderer().render(scene)
    assert ">7</text>" not in svg
    assert view_box(svg) == bare  # a stray label cannot inflate the viewBox


def test_off_lattice_edge_and_vertex_skipped() -> None:
    # A frame vertex whose canonical spelling carries an outside cell is
    # on-lattice and draws (legitimately expanding the viewBox); the
    # baseline includes it so the strays' contribution is isolated
    grid, base_scene = make_scene()
    frame_vertex = grid.vertex(grid.Cell(0, 2), "sw")
    base_scene.add(VertexMark(frame_vertex, glyph=Glyph("#")))
    base_svg = SvgRenderer().render(base_scene)
    assert ">#</text>" in base_svg

    scene = Scene(grid)
    scene.add(
        VertexMark(frame_vertex, glyph=Glyph("#")),
        EdgeSegment(Edge(grid.Cell(0, 7), "n")),
        EdgeMark(Edge(grid.Cell(0, 7), "s"), glyph=Glyph("*")),
        VertexMark(Vertex(grid.Cell(0, 7), "nw"), glyph=Glyph("*")),
    )
    svg = SvgRenderer().render(scene)
    assert ">*</text>" not in svg and 'class="edge"' not in svg
    assert view_box(svg) == view_box(base_svg)  # off-lattice strays cannot inflate the viewBox


def test_out_of_grid_elements_are_skipped() -> None:
    grid, scene = make_scene()
    scene.add(CellFill(grid.Cell(0, 1), PaletteColor.GREEN))
    svg = SvgRenderer().render(scene)
    assert "<polygon" not in svg
    _grid, bare_scene = make_scene()
    assert view_box(svg) == view_box(SvgRenderer().render(bare_scene))


def test_substrate_flags() -> None:
    _grid, scene = make_scene(SceneStyle(hairline=False, heavy_frame=False, vertex_dots=True))
    svg = SvgRenderer().render(scene)
    assert 'class="lattice"' not in svg
    assert 'class="frame"' not in svg
    # 4x3 cells -> 5x4 lattice vertices, each a substrate dot
    assert svg.count("<circle") == 20


def test_layer_groups_are_ordered() -> None:
    grid, scene = make_scene()
    cells = list(grid.all_cells())
    # Insertion order deliberately reversed relative to paint order
    scene.add(CellGlyph(cells[0], Glyph("7")), CellFill(cells[0], PaletteColor.GREEN))
    svg = SvgRenderer().render(scene)
    base = svg.index('<g data-layer="base">')
    fill = svg.index('<g data-layer="fill">')
    glyph = svg.index('<g data-layer="glyph">')
    assert base < fill < glyph
