"""
The expanded rectangular ASCII layout: lanes, collapsing, junction
resolution, substrate lattices, vertex marks, and outside-label margins —
pinned as exact scene-to-picture pairs, plus byte-equality against the
boxed output of the previous renderer.
"""

import pytest

from aspuzzle.grids.rectangulargrid import RectangularGrid
from aspuzzle.grids.rendering import RenderSymbol
from aspuzzle.puzzle import Puzzle
from aspuzzle.rendering import (
    Backend,
    CellFill,
    CellGlyph,
    CellPath,
    EdgeSegment,
    EdgeWeight,
    Glyph,
    Lattice,
    Layer,
    OutsideLabel,
    PaletteColor,
    Scene,
    SceneStyle,
    Vertex,
    VertexMark,
)
from aspuzzle.rendering.ascii import AsciiRenderer


def make_scene(
    rows: int = 2,
    cols: int = 2,
    style: SceneStyle | None = None,
    backend_styles: dict[Backend, SceneStyle] | None = None,
) -> tuple[RectangularGrid, Scene]:
    grid = RectangularGrid(Puzzle(), rows=rows, cols=cols)
    scene = Scene(grid, style=style or SceneStyle(), backend_styles=backend_styles or {})
    return grid, scene


def render(scene: Scene) -> str:
    return AsciiRenderer(use_colors=False).render(scene)


def block_border_edges(grid: RectangularGrid, rows_per_box: int, cols_per_box: int) -> list[EdgeSegment]:
    """Interior box-boundary edges, the shape RegionBorderRule will emit."""
    edges = []
    for row in range(1, grid.rows + 1):
        for col in range(1, grid.cols + 1):
            if row % rows_per_box == 0 and row < grid.rows:
                edges.append(EdgeSegment(grid.edge(grid.Cell(row, col), "s"), layer=Layer.GRID_MARK))
            if col % cols_per_box == 0 and col < grid.cols:
                edges.append(EdgeSegment(grid.edge(grid.Cell(row, col), "e"), layer=Layer.GRID_MARK))
    return edges


def test_frame_only() -> None:
    _, scene = make_scene(style=SceneStyle(lattice=Lattice.FRAME))
    assert render(scene) == "┌───┐\n│. .│\n│. .│\n└───┘"


def test_heavy_frame() -> None:
    _, scene = make_scene(style=SceneStyle(lattice=Lattice.FRAME, frame_weight=EdgeWeight.HEAVY))
    assert render(scene) == "╔═══╗\n║. .║\n║. .║\n╚═══╝"


def test_full_lattice_wireframe() -> None:
    _, scene = make_scene(style=SceneStyle(lattice=Lattice.FULL))
    assert render(scene) == "┌─┬─┐\n│.│.│\n├─┼─┤\n│.│.│\n└─┴─┘"


def test_boxed_output_matches_old_renderer_bytes() -> None:
    """Frame + block-border edges reproduce the old draw_box output exactly,
    junctions included — generated by calling the old code path."""
    grid, scene = make_scene(rows=4, cols=4, style=SceneStyle(lattice=Lattice.FRAME))
    scene.add(*block_border_edges(grid, rows_per_box=2, cols_per_box=2))
    new = render(scene)

    old_grid = [[RenderSymbol(".") for _ in range(4)] for _ in range(4)]
    old_config = {"join_char": " ", "draw_box": True, "rows_per_box": 2, "cols_per_box": 2}
    old = grid._render_grid_with_boxes(old_grid, old_config, use_colors=False)
    assert new == old


def test_single_stroked_interior_lane_collapse() -> None:
    """One stroked interior lane materializes; every other lane collapses."""
    grid, scene = make_scene()
    scene.add(
        EdgeSegment(grid.edge(grid.Cell(1, 1), "s")),
        EdgeSegment(grid.edge(grid.Cell(1, 2), "s")),
    )
    assert render(scene) == ". .\n───\n. ."


def test_stroke_meeting_frame() -> None:
    """An interior stroke ending at the frame junctions correctly."""
    grid, scene = make_scene(style=SceneStyle(lattice=Lattice.FRAME))
    scene.add(
        EdgeSegment(grid.edge(grid.Cell(1, 1), "s")),
        EdgeSegment(grid.edge(grid.Cell(1, 2), "s")),
    )
    assert render(scene) == "┌───┐\n│. .│\n├───┤\n│. .│\n└───┘"


def test_closed_loop_with_gap_zero() -> None:
    """A Slitherlink-shaped loop around one cell of a 2x2 grid."""
    grid, scene = make_scene(style=SceneStyle(packed=True))
    for direction in ("n", "e", "s", "w"):
        scene.add(EdgeSegment(grid.edge(grid.Cell(1, 1), direction)))
    assert render(scene) == "┌─┐ \n│.│.\n└─┘ \n . ."


def test_vertex_dots_materialize_all_lanes() -> None:
    _, scene = make_scene(style=SceneStyle(vertex_dots=True))
    assert render(scene) == ". . .\n . . \n. . .\n . . \n. . ."


def test_vertex_mark_element() -> None:
    grid, scene = make_scene()
    scene.add(VertexMark(grid.vertex(grid.Cell(1, 1), "se"), glyph=Glyph("+")))
    assert render(scene) == ". .\n + \n. ."


def test_edge_color_carries_to_box_chars() -> None:
    grid, scene = make_scene()
    scene.add(EdgeSegment(grid.edge(grid.Cell(1, 1), "e"), color=PaletteColor.BRIGHT_YELLOW))
    colored = AsciiRenderer(use_colors=True).render(scene)
    assert "\033[93m│\033[0m" in colored


def test_mixed_weight_junction_heavy_wins() -> None:
    grid, scene = make_scene()
    scene.add(
        EdgeSegment(grid.edge(grid.Cell(1, 1), "s")),
        EdgeSegment(grid.edge(grid.Cell(1, 2), "s"), weight=EdgeWeight.HEAVY),
    )
    out = render(scene)
    assert "═" in out and "─" in out


def test_outside_labels_reserve_margins() -> None:
    _, scene = make_scene(style=SceneStyle(lattice=Lattice.FRAME))
    scene.add(
        OutsideLabel("s", 1, Glyph("2")),
        OutsideLabel("s", 2, Glyph("1")),
        OutsideLabel("e", 2, Glyph("3")),
    )
    assert render(scene) == "   2 1 \n  ┌───┐\n  │. .│\n3 │. .│\n  └───┘"


def test_svg_only_substrate_keeps_ascii_compact() -> None:
    """A lattice requested for SVG alone must not expand the ASCII layout."""
    _, scene = make_scene(
        backend_styles={Backend.SVG: SceneStyle(lattice=Lattice.FULL, vertex_dots=True)},
    )
    assert render(scene) == ". .\n. ."


def test_conformance_every_element_kind_renders() -> None:
    grid, scene = make_scene(rows=3, cols=3, style=SceneStyle(lattice=Lattice.FRAME))
    scene.add(
        CellGlyph(grid.Cell(1, 1), Glyph("5")),
        EdgeSegment(grid.edge(grid.Cell(2, 2), "n")),
        VertexMark(grid.vertex(grid.Cell(3, 3), "nw"), glyph=Glyph("+")),
        OutsideLabel("s", 2, Glyph("7")),
    )
    out = render(scene)
    assert "5" in out and "7" in out and "+" in out


def test_stacked_label_rings_unsupported() -> None:
    _, scene = make_scene()
    scene.add(OutsideLabel("s", 1, Glyph("2"), offset=1))
    with pytest.raises(NotImplementedError, match="rings"):
        render(scene)


def test_wide_top_labels_widen_pitch_instead_of_crashing() -> None:
    _, scene = make_scene()
    scene.add(OutsideLabel("s", 1, Glyph("12")), OutsideLabel("s", 2, Glyph("10")))
    out = render(scene)
    assert out.splitlines()[0] == "12 10"


def test_isolated_edge_covers_only_its_own_cell() -> None:
    grid, scene = make_scene(rows=2, cols=3)
    scene.add(EdgeSegment(grid.edge(grid.Cell(1, 2), "n")))
    assert render(scene).splitlines()[0] == "  ─  "


def test_fills_bridge_gaps_between_equal_neighbors() -> None:
    grid, scene = make_scene(rows=1, cols=2)
    scene.add(
        CellFill(grid.Cell(1, 1), PaletteColor.GREEN),
        CellFill(grid.Cell(1, 2), PaletteColor.GREEN),
        EdgeSegment(grid.edge(grid.Cell(1, 1), "n")),  # materializes a lane: expanded layout
    )
    colored = AsciiRenderer(use_colors=True).render(scene)
    content_row = colored.splitlines()[1]
    # cell, gap, cell — the gap char carries the shared background too
    assert content_row.count("\033[42m") == 3


def test_fills_flood_solid_block_through_full_lattice() -> None:
    grid, scene = make_scene(style=SceneStyle(lattice=Lattice.FULL))
    for row in (1, 2):
        for col in (1, 2):
            scene.add(CellFill(grid.Cell(row, col), PaletteColor.GREEN))
    colored = AsciiRenderer(use_colors=True).render(scene)
    # the interior 3x3 (cells plus every char between them) carries the
    # background; the outer lattice ring has no filled flank and stays bare
    assert colored.count("\033[42m") == 9
    for line in colored.splitlines()[1:4]:
        assert line.count("\033[42m") == 3


def test_out_of_grid_vertex_mark_skipped_silently() -> None:
    grid, scene = make_scene(rows=3, cols=3)
    scene.add(VertexMark(grid.vertex(grid.Cell(1, 1), "nw")), VertexMark(Vertex(grid.Cell(0, 7), "nw")))
    out = render(scene)  # no crash; the in-grid mark renders
    assert "." in out


def test_singleton_path_renders_stub() -> None:
    grid, scene = make_scene()
    scene.add(CellPath(grid.Cell(1, 1), frozenset({"e"})))
    assert "╶" in render(scene)


def test_label_index_beyond_grid_skipped_silently() -> None:
    _, scene = make_scene()
    scene.add(OutsideLabel("e", 5, Glyph("9")), OutsideLabel("e", 1, Glyph("7")))
    out = render(scene)
    assert "7" in out and "9" not in out
